Algoritmo sin_titulo
	Escribir "HALLAR EL PERIMETRO Y AREA DE UN RECTNAGULO"
	ESCRIBIR "DAME BASE"
	LEER B
	ESCRIBIR "DAME ALTURA"
	LEER A
	P <- 2 * (B + A)
	A <- B * A
	ESCRIBIR "LA AREA ES:", A
	ESCRIBIR "EL PERIMETRO ES:", P
FinAlgoritmo
