Algoritmo sin_titulo
	ESCRIBIR "DAME LOS LADOS"
	LEER L
	ESCRIBIR "DAME EL APOTEMA"
	LEER AD
	P <- L*5
	A <- (P * AD)/2
	ESCRIBIR "EL PERIMETRO ES:", P
	ESCRIBIR "EL AREA DE UN PENTAGONO ES:", A
FinAlgoritmo
